version: "3"

includes:
  docker: .taskfiles/Docker.yml
  test: .taskfiles/Test.yml
  app: .taskfiles/App.yml

tasks:
  default:
    desc: List all available modular automation tasks
    cmds:
      - task --list
